services:
  app:
    build: .
    image: speed007/debrid-proxy:latest
    container_name: debrid-proxy
    restart: unless-stopped
    environment:
      - RD_API_KEY=${RD_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - CACHE_TTL=${CACHE_TTL:-3600}
      - RATE_LIMIT=${RATE_LIMIT:-30/60}
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: debrid-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  prometheus:
    image: prom/prometheus:latest
    container_name: debrid-monitor
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: debrid-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./monitoring/grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    depends_on:
      - prometheus

volumes:
  redis-data:
  prometheus-data:
  grafana-storage:
