# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'debrid-proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['debrid-proxy:8000']  # Matches your docker-compose service name
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'debrid-proxy-service'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
